### ISSUE TITLE
Problemas en la ejecución

### ISSUE THREAD

**Issue by diagmatrix** [delightfulagony/ed_p3#2]
Se deben de arreglar los siguientes problemas:

- [ ] Mala asignación del máximo de la pila.

- [ ] El programa da error si intentamos hacer un borrado de bastantes elementos

**Comment by delightfulagony** [comment]
Bastantes elementos son n>2 xD xD

A veces da el error:
```pila_max: ./src/VDG.cpp:103: T& VectorDinamico<T>::operator[](int) [with T = int]: Assertion `0 <= i && i < num_comp' failed.
Aborted (core dumped)```
Y otras veces simplemente vuelve al principio y ejecuta la secuencia inicial un par de veces-

**Comment by diagmatrix** [comment]
He creado un nuevo elemento de la clase PilaMax, llamado elementos que cuenta el número de elementos. No tiene ninguna "utilidad" salvo la de tener controlado en todo momento las dimensiones pila y max, asegurándose de que ambas tengan el mismo número de elementos
